/********************************************************************
* DictOutput.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DictOutput.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDictOutput();
extern void G__cpp_setup_inheritanceDictOutput();
extern void G__cpp_setup_typetableDictOutput();
extern void G__cpp_setup_memvarDictOutput();
extern void G__cpp_setup_globalDictOutput();
extern void G__cpp_setup_memfuncDictOutput();
extern void G__cpp_setup_funcDictOutput();
extern void G__set_cpp_environmentDictOutput();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Event.h"
#include "Hits30x30.h"
#include "simulatedEvent.h"
#include "Track.h"
#include "patternRecognitionData.h"
#include "analysisData.h"
#include "B1Particle.h"
#include "B1DetectorResponse.h"
#include "particlePF.h"
#include "DataManager.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DictOutputLN_TClass;
extern G__linked_taginfo G__DictOutputLN_TBuffer;
extern G__linked_taginfo G__DictOutputLN_TMemberInspector;
extern G__linked_taginfo G__DictOutputLN_TObject;
extern G__linked_taginfo G__DictOutputLN_string;
extern G__linked_taginfo G__DictOutputLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictOutputLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictOutputLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DictOutputLN_TFile;
extern G__linked_taginfo G__DictOutputLN_Hits30x30;
extern G__linked_taginfo G__DictOutputLN_TRandom2;
extern G__linked_taginfo G__DictOutputLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TVector3;
extern G__linked_taginfo G__DictOutputLN_B1Particle;
extern G__linked_taginfo G__DictOutputLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictOutputLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictOutputLN_B1DetectorResponse;
extern G__linked_taginfo G__DictOutputLN_simulatedEvent;
extern G__linked_taginfo G__DictOutputLN_vectorlEB1ParticlemUcOallocatorlEB1ParticlemUgRsPgR;
extern G__linked_taginfo G__DictOutputLN_vectorlEB1ParticlemUcOallocatorlEB1ParticlemUgRsPgRcLcLiterator;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlEB1ParticlemUcOallocatorlEB1ParticlemUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictOutputLN_Track;
extern G__linked_taginfo G__DictOutputLN_patternRecognitionData;
extern G__linked_taginfo G__DictOutputLN_vectorlETrackmUcOallocatorlETrackmUgRsPgR;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlETrackmUcOallocatorlETrackmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictOutputLN_particlePF;
extern G__linked_taginfo G__DictOutputLN_analysisData;
extern G__linked_taginfo G__DictOutputLN_vectorlEparticlePFcOallocatorlEparticlePFgRsPgR;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlEparticlePFcOallocatorlEparticlePFgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictOutputLN_Event;
extern G__linked_taginfo G__DictOutputLN_TTree;
extern G__linked_taginfo G__DictOutputLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__DictOutputLN_DataManager;

/* STUB derived class for protected member access */
typedef vector<B1Particle*,allocator<B1Particle*> > G__vectorlEB1ParticlemUcOallocatorlEB1ParticlemUgRsPgR;
